steps:
  # Step 1: Set up the Python environment
  - name: 'python:3.8'
    id: 'Set up Python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y python3-dev python3-pip
        pip3 install --upgrade pip

  # Step 2: Install dependencies
  - name: 'python:3.8'
    id: 'Install dependencies'
    entrypoint: 'pip'
    args:
      - 'install'
      - '-r'
      - 'requirements.txt'  # Adjust the path to your requirements file

  # Step 3: Build the Python application
  - name: 'python:3.8'
    id: 'Build Python application'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd hello_app
        export FLASK_APP=webapp
        flask run
